UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-03-22", `dateFin` = "19-06-04" WHERE (`idEtudiant` = 1);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Stage ", `dateDebut` = "19-03-28", `dateFin` = "19-07-08" WHERE (`idEtudiant` = 2);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Autre", `dateDebut` = "19-01-11", `dateFin` = "19-09-04" WHERE (`idEtudiant` = 3);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-03-19", `dateFin` = "19-06-08" WHERE (`idEtudiant` = 4);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-02-09", `dateFin` = "19-07-12" WHERE (`idEtudiant` = 5);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-03-23", `dateFin` = "19-09-22" WHERE (`idEtudiant` = 6);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Autre", `dateDebut` = "19-01-27", `dateFin` = "19-07-15" WHERE (`idEtudiant` = 7);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Stage ", `dateDebut` = "19-02-20", `dateFin` = "19-06-02" WHERE (`idEtudiant` = 8);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-01-27", `dateFin` = "19-08-20" WHERE (`idEtudiant` = 9);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-01-26", `dateFin` = "19-08-30" WHERE (`idEtudiant` = 10);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-03-08", `dateFin` = "19-06-11" WHERE (`idEtudiant` = 11);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Autre", `dateDebut` = "19-03-27", `dateFin` = "19-06-08" WHERE (`idEtudiant` = 12);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Stage ", `dateDebut` = "19-02-20", `dateFin` = "19-09-26" WHERE (`idEtudiant` = 13);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-01-26", `dateFin` = "19-08-01" WHERE (`idEtudiant` = 14);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Autre", `dateDebut` = "19-01-29", `dateFin` = "19-07-05" WHERE (`idEtudiant` = 15);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-02-16", `dateFin` = "19-09-05" WHERE (`idEtudiant` = 16);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = "Semestre ", `dateDebut` = "19-03-20", `dateFin` = "19-07-17" WHERE (`idEtudiant` = 17);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Stage ", `dateDebut` = "19-02-18", `dateFin` = "19-08-05" WHERE (`idEtudiant` = 18);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = "Semestre ", `dateDebut` = "19-04-28", `dateFin` = "19-09-22" WHERE (`idEtudiant` = 19);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-04-23", `dateFin` = "19-08-17" WHERE (`idEtudiant` = 20);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = "Semestre ", `dateDebut` = "19-02-17", `dateFin` = "19-09-12" WHERE (`idEtudiant` = 21);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-01-10", `dateFin` = "19-09-08" WHERE (`idEtudiant` = 22);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Autre", `dateDebut` = "19-03-06", `dateFin` = "19-06-17" WHERE (`idEtudiant` = 23);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-03-02", `dateFin` = "19-07-05" WHERE (`idEtudiant` = 24);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = "Semestre ", `dateDebut` = "19-04-29", `dateFin` = "19-07-21" WHERE (`idEtudiant` = 25);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Autre", `dateDebut` = "19-01-17", `dateFin` = "19-08-19" WHERE (`idEtudiant` = 26);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = "Semestre ", `dateDebut` = "19-02-16", `dateFin` = "19-09-16" WHERE (`idEtudiant` = 27);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Autre", `dateDebut` = "19-01-24", `dateFin` = "19-06-11" WHERE (`idEtudiant` = 28);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-01-24", `dateFin` = "19-09-19" WHERE (`idEtudiant` = 29);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = "Semestre ", `dateDebut` = "19-04-22", `dateFin` = "19-07-04" WHERE (`idEtudiant` = 30);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Stage ", `dateDebut` = "19-02-03", `dateFin` = "19-09-04" WHERE (`idEtudiant` = 31);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = "Semestre ", `dateDebut` = "19-03-31", `dateFin` = "19-08-22" WHERE (`idEtudiant` = 32);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-04-11", `dateFin` = "19-08-13" WHERE (`idEtudiant` = 33);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-01-14", `dateFin` = "19-08-14" WHERE (`idEtudiant` = 34);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Stage ", `dateDebut` = "19-01-15", `dateFin` = "19-08-31" WHERE (`idEtudiant` = 35);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-01-30", `dateFin` = "19-06-08" WHERE (`idEtudiant` = 36);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Autre", `dateDebut` = "19-01-04", `dateFin` = "19-08-18" WHERE (`idEtudiant` = 37);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Stage ", `dateDebut` = "19-01-08", `dateFin` = "19-07-21" WHERE (`idEtudiant` = 38);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = "Semestre ", `dateDebut` = "19-01-16", `dateFin` = "19-09-21" WHERE (`idEtudiant` = 39);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Stage ", `dateDebut` = "19-01-10", `dateFin` = "19-08-27" WHERE (`idEtudiant` = 40);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Autre", `dateDebut` = "19-03-25", `dateFin` = "19-07-24" WHERE (`idEtudiant` = 41);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-04-09", `dateFin` = "19-07-19" WHERE (`idEtudiant` = 42);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = "Semestre ", `dateDebut` = "19-03-18", `dateFin` = "19-09-26" WHERE (`idEtudiant` = 43);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Stage ", `dateDebut` = "19-03-03", `dateFin` = "19-07-27" WHERE (`idEtudiant` = 44);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = "Semestre ", `dateDebut` = "19-03-29", `dateFin` = "19-07-23" WHERE (`idEtudiant` = 45);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-02-03", `dateFin` = "19-06-15" WHERE (`idEtudiant` = 46);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-02-27", `dateFin` = "19-08-20" WHERE (`idEtudiant` = 47);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Stage ", `dateDebut` = "19-03-19", `dateFin` = "19-09-22" WHERE (`idEtudiant` = 48);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Autre", `dateDebut` = "19-04-09", `dateFin` = "19-07-17" WHERE (`idEtudiant` = 49);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = "Semestre ", `dateDebut` = "19-02-22", `dateFin` = "19-07-06" WHERE (`idEtudiant` = 50);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = "Semestre ", `dateDebut` = "19-01-26", `dateFin` = "19-08-25" WHERE (`idEtudiant` = 51);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-02-19", `dateFin` = "19-08-16" WHERE (`idEtudiant` = 52);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-03-22", `dateFin` = "19-08-25" WHERE (`idEtudiant` = 53);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Stage ", `dateDebut` = "19-02-22", `dateFin` = "19-08-08" WHERE (`idEtudiant` = 54);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-01-12", `dateFin` = "19-07-07" WHERE (`idEtudiant` = 55);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-02-21", `dateFin` = "19-08-14" WHERE (`idEtudiant` = 56);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Stage ", `dateDebut` = "19-03-08", `dateFin` = "19-09-07" WHERE (`idEtudiant` = 57);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Stage ", `dateDebut` = "19-01-14", `dateFin` = "19-07-19" WHERE (`idEtudiant` = 58);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = "Semestre ", `dateDebut` = "19-01-20", `dateFin` = "19-08-10" WHERE (`idEtudiant` = 59);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = "Semestre ", `dateDebut` = "19-04-01", `dateFin` = "19-08-11" WHERE (`idEtudiant` = 60);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-04-08", `dateFin` = "19-08-06" WHERE (`idEtudiant` = 61);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Stage ", `dateDebut` = "19-01-16", `dateFin` = "19-07-29" WHERE (`idEtudiant` = 62);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-03-08", `dateFin` = "19-07-04" WHERE (`idEtudiant` = 63);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-02-24", `dateFin` = "19-08-25" WHERE (`idEtudiant` = 64);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Autre", `dateDebut` = "19-01-06", `dateFin` = "19-07-28" WHERE (`idEtudiant` = 65);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = "Semestre ", `dateDebut` = "19-04-14", `dateFin` = "19-08-07" WHERE (`idEtudiant` = 66);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-04-02", `dateFin` = "19-09-11" WHERE (`idEtudiant` = 67);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-04-01", `dateFin` = "19-09-11" WHERE (`idEtudiant` = 68);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Stage ", `dateDebut` = "19-04-08", `dateFin` = "19-06-01" WHERE (`idEtudiant` = 69);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-01-24", `dateFin` = "19-09-27" WHERE (`idEtudiant` = 70);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = "Semestre ", `dateDebut` = "19-04-04", `dateFin` = "19-06-11" WHERE (`idEtudiant` = 71);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = "Semestre ", `dateDebut` = "19-03-16", `dateFin` = "19-09-25" WHERE (`idEtudiant` = 72);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-01-25", `dateFin` = "19-09-15" WHERE (`idEtudiant` = 73);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-04-22", `dateFin` = "19-06-18" WHERE (`idEtudiant` = 74);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-02-07", `dateFin` = "19-06-17" WHERE (`idEtudiant` = 75);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Autre", `dateDebut` = "19-01-30", `dateFin` = "19-07-24" WHERE (`idEtudiant` = 76);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-03-09", `dateFin` = "19-06-11" WHERE (`idEtudiant` = 77);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = "Semestre ", `dateDebut` = "19-04-09", `dateFin` = "19-07-13" WHERE (`idEtudiant` = 78);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-04-25", `dateFin` = "19-06-23" WHERE (`idEtudiant` = 79);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-02-21", `dateFin` = "19-08-10" WHERE (`idEtudiant` = 80);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Autre", `dateDebut` = "19-04-27", `dateFin` = "19-06-07" WHERE (`idEtudiant` = 81);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-01-20", `dateFin` = "19-09-12" WHERE (`idEtudiant` = 82);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-01-23", `dateFin` = "19-08-30" WHERE (`idEtudiant` = 83);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = "Semestre ", `dateDebut` = "19-01-05", `dateFin` = "19-09-15" WHERE (`idEtudiant` = 84);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = "Semestre ", `dateDebut` = "19-02-26", `dateFin` = "19-09-06" WHERE (`idEtudiant` = 85);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-02-08", `dateFin` = "19-07-10" WHERE (`idEtudiant` = 86);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-03-25", `dateFin` = "19-09-01" WHERE (`idEtudiant` = 87);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-04-06", `dateFin` = "19-08-06" WHERE (`idEtudiant` = 88);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Autre", `dateDebut` = "19-01-05", `dateFin` = "19-06-09" WHERE (`idEtudiant` = 89);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = "Semestre ", `dateDebut` = "19-01-21", `dateFin` = "19-06-29" WHERE (`idEtudiant` = 90);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-03-11", `dateFin` = "19-08-03" WHERE (`idEtudiant` = 91);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-04-12", `dateFin` = "19-09-23" WHERE (`idEtudiant` = 92);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = "Semestre ", `dateDebut` = "19-02-26", `dateFin` = "19-09-13" WHERE (`idEtudiant` = 93);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = " Stage ", `dateDebut` = "19-01-21", `dateFin` = "19-07-07" WHERE (`idEtudiant` = 94);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Autre", `dateDebut` = "19-01-30", `dateFin` = "19-09-19" WHERE (`idEtudiant` = 95);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = "Semestre ", `dateDebut` = "19-01-19", `dateFin` = "19-08-14" WHERE (`idEtudiant` = 96);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 1, `typeValidation` = " Stage ", `dateDebut` = "19-01-31", `dateFin` = "19-06-28" WHERE (`idEtudiant` = 97);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 0, `typeValidation` = "Semestre ", `dateDebut` = "19-02-16", `dateFin` = "19-07-03" WHERE (`idEtudiant` = 98);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Stage ", `dateDebut` = "19-04-27", `dateFin` = "19-07-21" WHERE (`idEtudiant` = 99);
UPDATE `renkinjutsushi`.`etudiant` SET `semestreValide` = 2, `typeValidation` = " Stage ", `dateDebut` = "19-04-22", `dateFin` = "19-09-09" WHERE (`idEtudiant` = 100);