export interface EtudiantSimp {
  idEtudiant: number,
  nom: string,
  prenom: string,
  promo: string,
  photo: { type: string, data: number[] },
  // specialite: Specialite,
  specialite: number,
  commentaire: string,
  // etat: Etat,
  etat: number,
  semainesRestantes: number,
  dateDebut: Date,
  dateFin: Date,
  // pays: Pays,
  pays: number,
  obtenuVia: string,
  mail: string,
  annee: number
}
